import type {
  CmsBlogPostRow,
  CmsDoctorRow,
  CmsHomeSectionRow,
  CmsMediaRow,
  CmsServiceRow,
  CmsTestimonialRow,
} from './cms.types';

/** Mirrors database/06-cms-seed.sql for USE_PERSISTENCE=false. */
export const CMS_SEED_MEDIA: CmsMediaRow[] = [
  {
    id: 'a0000001-0000-4000-8000-000000000001',
    storagePath: null,
    publicUrl:
      'https://api.dicebear.com/7.x/micah/svg?seed=DrLunaBrightmind&backgroundColor=b6e3f4',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Dr. Luna Brightmind',
    altEn: 'Cartoon avatar — Dr. Luna Brightmind',
    altEs: 'Avatar cartoon — Dra. Luna Brightmind',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000002',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=MiloDreamleaf&backgroundColor=d1f4e0',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Milo Dreamleaf',
    altEn: 'Cartoon avatar — Milo Dreamleaf',
    altEs: 'Avatar cartoon — Milo Dreamleaf',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000003',
    storagePath: null,
    publicUrl:
      'https://api.dicebear.com/7.x/micah/svg?seed=AlexCloudwalker&backgroundColor=e8d5f2',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Alex Cloudwalker',
    altEn: 'Cartoon avatar — Alex Cloudwalker',
    altEs: 'Avatar cartoon — Alex Cloudwalker',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000004',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientAvery&backgroundColor=fff4e6',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000005',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientJordan&backgroundColor=f0f4ff',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000006',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientSam&backgroundColor=fce4ec',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
];

const now = () => new Date().toISOString();

export const CMS_SEED_DOCTORS: CmsDoctorRow[] = [
  {
    id: 'd0000001-0000-4000-8000-000000000001',
    slug: 'luna',
    sortOrder: 0,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000001',
    nameFr: 'Dr. Luna Brightmind',
    nameEn: 'Dr. Luna Brightmind',
    nameEs: 'Dra. Luna Brightmind',
    roleFr: 'Psychologue',
    roleEn: 'Psychologist',
    roleEs: 'Psicóloga',
    bioFr: '<p>Approche intégrative TCC et pleine conscience. Focus sur l’anxiété et les transitions de vie.</p>',
    bioEn: '<p>Integrative CBT and mindfulness. Focus on anxiety and life transitions.</p>',
    bioEs: '<p>TCC integrativa y mindfulness. Ansiedad y transiciones vitales.</p>',
    illustrationNote: 'Semi-flat portrait, soft teal and cream palette, warm smile — calm professionalism.',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'd0000001-0000-4000-8000-000000000002',
    slug: 'milo',
    sortOrder: 1,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000002',
    nameFr: 'Milo Dreamleaf',
    nameEn: 'Milo Dreamleaf',
    nameEs: 'Milo Dreamleaf',
    roleFr: 'Travailleur social clinique',
    roleEn: 'Clinical social worker',
    roleEs: 'Trabajador social clínico',
    bioFr: '<p>Soutien aux familles et aux jeunes; perspective systémique.</p>',
    bioEn: '<p>Supports families and youth; systemic lens.</p>',
    bioEs: '<p>Apoyo a familias y jóvenes; enfoque sistémico.</p>',
    illustrationNote: 'Pastel greens, seated figure with plant motif — inclusive silhouette.',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'd0000001-0000-4000-8000-000000000003',
    slug: 'alex',
    sortOrder: 2,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000003',
    nameFr: 'Alex Cloudwalker',
    nameEn: 'Alex Cloudwalker',
    nameEs: 'Alex Cloudwalker',
    roleFr: 'Psychothérapeute',
    roleEn: 'Psychotherapist',
    roleEs: 'Psicoterapeuta',
    bioFr: '<p>Affirmatif 2SLGBTQ+; thérapie axée sur les forces et la résilience.</p>',
    bioEn: '<p>2SLGBTQ+-affirming; strengths-based, resilience-focused care.</p>',
    bioEs: '<p>Afirmativo 2SLGBTQ+; enfoque en fortalezas y resiliencia.</p>',
    illustrationNote: 'Soft lavender and sky blue, abstract path motif — recovery-oriented.',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_SERVICES: CmsServiceRow[] = [
  {
    id: 'e0000001-0000-4000-8000-000000000001',
    slug: 'individual',
    sortOrder: 0,
    titleFr: 'Thérapie individuelle',
    titleEn: 'Individual therapy',
    titleEs: 'Terapia individual',
    bodyFr: '<p>Suivi psychologique individuel (adultes).</p>',
    bodyEn: '<p>One-to-one psychological care (adults).</p>',
    bodyEs: '<p>Atención psicológica individual (adultos).</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000002',
    slug: 'couples',
    sortOrder: 1,
    titleFr: 'Couple',
    titleEn: 'Couples',
    titleEs: 'Pareja',
    bodyFr: '<p>Soutien relationnel et médiation thérapeutique.</p>',
    bodyEn: '<p>Relationship support and therapeutic mediation.</p>',
    bodyEs: '<p>Apoyo relacional y mediación terapéutica.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000003',
    slug: 'family',
    sortOrder: 2,
    titleFr: 'Famille',
    titleEn: 'Family',
    titleEs: 'Familia',
    bodyFr: '<p>Séances impliquant plusieurs membres de la famille.</p>',
    bodyEn: '<p>Sessions involving multiple family members.</p>',
    bodyEs: '<p>Sesiones con varios miembros de la familia.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000004',
    slug: 'youth',
    sortOrder: 3,
    titleFr: 'Jeunesse (12–17)',
    titleEn: 'Youth (12–17)',
    titleEs: 'Juventud (12–17)',
    bodyFr: '<p>Accompagnement adapté aux adolescents.</p>',
    bodyEn: '<p>Developmentally appropriate adolescent support.</p>',
    bodyEs: '<p>Acompañamiento adaptado a adolescentes.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000005',
    slug: 'anxiety_mood',
    sortOrder: 4,
    titleFr: 'Anxiété & humeur',
    titleEn: 'Anxiety & mood',
    titleEs: 'Ansiedad y estado de ánimo',
    bodyFr: '<p>Symptômes d’anxiété, dépression, stress.</p>',
    bodyEn: '<p>Anxiety, depression, and stress-related symptoms.</p>',
    bodyEs: '<p>Ansiedad, depresión y estrés.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000006',
    slug: 'adhd_focus',
    sortOrder: 5,
    titleFr: 'TDAH / attention',
    titleEn: 'ADHD / attention',
    titleEs: 'TDAH / atención',
    bodyFr: '<p>Difficultés d’attention, organisation, exécution.</p>',
    bodyEn: '<p>Attention, organization, and executive functioning.</p>',
    bodyEs: '<p>Atención, organización y funciones ejecutivas.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000007',
    slug: 'trauma',
    sortOrder: 6,
    titleFr: 'Trauma informé',
    titleEn: 'Trauma-informed',
    titleEs: 'Informado en trauma',
    bodyFr: '<p>Approches sensibles aux vécu traumatiques.</p>',
    bodyEn: '<p>Trauma-sensitive clinical approaches.</p>',
    bodyEs: '<p>Enfoques sensibles al trauma.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000008',
    slug: 'assessment',
    sortOrder: 7,
    titleFr: 'Évaluation',
    titleEn: 'Assessment',
    titleEs: 'Evaluación',
    bodyFr: '<p>Bilan orienté diagnostic ou orientation de services.</p>',
    bodyEn: '<p>Diagnostic-oriented or service-planning assessment.</p>',
    bodyEs: '<p>Evaluación orientada al diagnóstico o planificación.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000009',
    slug: 'other',
    sortOrder: 8,
    titleFr: 'Autre',
    titleEn: 'Other',
    titleEs: 'Otro',
    bodyFr: '<p>Précisez dans les notes au clinicien.</p>',
    bodyEn: '<p>Add details in notes to clinician.</p>',
    bodyEs: '<p>Detalles en notas al clínico.</p>',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_TESTIMONIALS: CmsTestimonialRow[] = [
  {
    id: 'f0000001-0000-4000-8000-000000000001',
    sortOrder: 0,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000004',
    authorFr: 'Avery L. (fictif)',
    authorEn: 'Avery L. (fictional)',
    authorEs: 'Avery L. (ficticio)',
    quoteFr: '<p>Interface claire pour la démo — aucune donnée réelle, mais le parcours est rassurant.</p>',
    quoteEn: '<p>Clear interface for the demo — no real data, but the flow feels reassuring.</p>',
    quoteEs: '<p>Interfaz clara para la demo — sin datos reales, pero el flujo transmite calma.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'f0000001-0000-4000-8000-000000000002',
    sortOrder: 1,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000005',
    authorFr: 'Jordan M. (fictif)',
    authorEn: 'Jordan M. (fictional)',
    authorEs: 'Jordan M. (ficticio)',
    quoteFr: '<p>La prise de rendez-vous guidée est utile pour valider l’ergonomie.</p>',
    quoteEn: '<p>Guided booking helps validate the ergonomics.</p>',
    quoteEs: '<p>La reserva guiada ayuda a validar la ergonomía.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'f0000001-0000-4000-8000-000000000003',
    sortOrder: 2,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000006',
    authorFr: 'Sam R. (fictif)',
    authorEn: 'Sam R. (fictional)',
    authorEs: 'Sam R. (ficticio)',
    quoteFr: '<p>Contenu trilingue cohérent pour une maquette pédagogique.</p>',
    quoteEn: '<p>Consistent trilingual content for an educational mockup.</p>',
    quoteEs: '<p>Contenido trilingüe coherente para una maqueta educativa.</p>',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_HOME: CmsHomeSectionRow[] = [
  {
    id: 'b0000001-0000-4000-8000-000000000001',
    sortOrder: 0,
    sectionType: 'hero',
    payload: {
      title: {
        fr: 'Clinique virtuelle de psychologie — Montréal',
        en: 'Virtual psychology clinic — Montreal',
        es: 'Clínica virtual de psicología — Montreal',
      },
      lead: {
        fr: 'Accompagnement psychologique téléphonique et en visioconférence. Maquette à des fins de démonstration — aucun service clinique réel.',
        en: 'Telephone and video support (mockup). Demonstration only — no real clinical service.',
        es: 'Acompañamiento por teléfono y videollamada. Maqueta de demostración — sin servicio clínico real.',
      },
      ctaPrimary: {
        label: { fr: 'Créer un compte fictif', en: 'Create a demo account', es: 'Cuenta de demostración' },
        href: '#/register',
      },
      ctaSecondary: {
        label: { fr: 'Avis légaux', en: 'Legal notices', es: 'Avisos legales' },
        href: '#/legal',
      },
      ctaBook: {
        label: { fr: 'Prendre rendez-vous', en: 'Book a session', es: 'Reservar' },
        href: '#/login',
      },
    },
    published: true,
    updatedAt: now(),
  },
  {
    id: 'b0000001-0000-4000-8000-000000000002',
    sortOrder: 1,
    sectionType: 'feature_grid',
    payload: {
      cards: [
        {
          title: { fr: 'Services', en: 'Services', es: 'Servicios' },
          blurb: {
            fr: 'Les catégories relient le formulaire de réservation une fois connecté.',
            en: 'Categories connect to booking after sign-in.',
            es: 'Las categorías enlazan con la reserva tras iniciar sesión.',
          },
          href: '#/services',
        },
        {
          title: { fr: 'Équipe', en: 'Team', es: 'Equipo' },
          blurb: {
            fr: 'Personnages fictifs et avatars cartoon.',
            en: 'Fictional characters and cartoon avatars.',
            es: 'Personajes ficticios y avatares cartoon.',
          },
          href: '#/team',
        },
        {
          title: { fr: 'Blogue', en: 'Blog', es: 'Blog' },
          blurb: {
            fr: 'Articles courts citant OMS, NIH/NIMH, CDC, NHLBI, etc.',
            en: 'Short posts citing WHO, NIH/NIMH, CDC, NHLBI, and related agencies.',
            es: 'Textos breves con citas a OMS, NIH/NIMH, CDC, NHLBI, etc.',
          },
          href: '#/blog',
        },
      ],
    },
    published: true,
    updatedAt: now(),
  },
  {
    id: 'b0000001-0000-4000-8000-000000000003',
    sortOrder: 2,
    sectionType: 'testimonial_strip',
    payload: {
      heading: {
        fr: 'Témoignages (fictifs)',
        en: 'Testimonials (fictional)',
        es: 'Testimonios (ficticios)',
      },
    },
    published: true,
    updatedAt: now(),
  },
];

/** Educational spotlights citing public-health sources; excerpts used where redistribution is explicitly permitted or U.S. government works (PD). */
export const CMS_SEED_BLOG: CmsBlogPostRow[] = [
  {
    id: 'c0000001-0000-4000-8000-000000000001',
    slug: 'nimh-seasonal-affective-disorder',
    datePublished: '2026-01-10',
    titleFr: 'Trouble affectif saisonnier — rappels du NIMH',
    titleEn: 'Seasonal affective disorder: NIMH overview',
    titleEs: 'Trastorno afectivo estacional — resumen NIMH',
    excerptFr: 'Résumé pédagogique à partir du National Institute of Mental Health (USA). Sans avis médical.',
    excerptEn: 'Lay summary sourced from NIH/NIMH (U.S.). Not medical advice.',
    excerptEs: 'Resumen educativo basado en NIMH (EE. UU.). No es consejo médico.',
    bodyFr:
      '<p>Résumé éducatif pour la démo PsyNova. La citation ci-dessous provient des contenus pour le grand public du NIMH.</p><blockquote cite="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder"><p>SAD is a type of depression characterized by a recurrent seasonal pattern, with symptoms lasting about 4–5 months out of the year.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder" rel="noopener noreferrer">National Institute of Mental Health (NIH)</a> — Consulté mai&nbsp;2026. Œuvres du gouvernement fédéral des États-Unis.</p>',
    bodyEn:
      '<p>Educational summary for PsyNova’s public blog. Below, a verbatim excerpt drawn from NIH/NIMH consumer information (U.S. government work).</p><blockquote cite="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder"><p>SAD is a type of depression characterized by a recurrent seasonal pattern, with symptoms lasting about 4–5 months out of the year.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder" rel="noopener noreferrer">National Institute of Mental Health (NIH)</a>. Accessed May&nbsp;2026. U.S. government work.</p><p>This page is informational only and does not replace care from a qualified clinician.</p>',
    bodyEs:
      '<p>Resumen educativo. La cita siguiente proviene del material para el público del NIMH (inglés original).</p><blockquote cite="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder"><p>SAD is a type of depression characterized by a recurrent seasonal pattern, with symptoms lasting about 4–5 months out of the year.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nimh.nih.gov/health/publications/seasonal-affective-disorder" rel="noopener noreferrer">NIMH (NIH)</a>, consultado en mayo de 2026.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000002',
    slug: 'cdc-mental-health-overview',
    datePublished: '2026-01-12',
    titleFr: 'Qu’est-ce que la santé mentale&nbsp;? (CDC)',
    titleEn: 'What counts as mental health — CDC overview',
    titleEs: '¿Qué es la salud mental? — CDC',
    excerptFr: 'Définition grand public du Centers for Disease Control and Prevention (É.-U.).',
    excerptEn: 'Plain-language definition from CDC mental-health landing pages.',
    excerptEs: 'Defensa del bienestar mental según los CDC.',
    bodyFr:
      '<p>Résumé pour lecteurs nord-américains&nbsp;: les CDC précisent ce que recouvre la santé mentale avant d’aborder les filières de soins.</p><blockquote cite="https://www.cdc.gov/mental-health/index.html"><p>Mental health includes a person’s emotional, psychological, and social well-being.</p></blockquote><p><strong>Source&nbsp;:</strong> Centers for Disease Control and Prevention, <em>Mental Health</em>, <a href="https://www.cdc.gov/mental-health/index.html" rel="noopener noreferrer">cdc.gov/mental-health</a>, consulté mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Federal public-health agencies routinely publish broad definitions before linking to crisis resources and data programs.</p><blockquote cite="https://www.cdc.gov/mental-health/index.html"><p>Mental health includes a person’s emotional, psychological, and social well-being.</p></blockquote><p><strong>Source:</strong> Centers for Disease Control and Prevention (<a href="https://www.cdc.gov/mental-health/index.html" rel="noopener noreferrer">cdc.gov/mental-health</a>). Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.cdc.gov/mental-health/index.html"><p>Mental health includes a person’s emotional, psychological, and social well-being.</p></blockquote><p><strong>Fuente:</strong> CDC (<a href="https://www.cdc.gov/mental-health/index.html" rel="noopener noreferrer">cdc.gov</a>), mayo 2026.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000003',
    slug: 'nimh-depression-basics',
    datePublished: '2026-01-18',
    titleFr: 'La dépression (trouble dépressif majeur), selon le NIMH',
    titleEn: 'Depression basics from NIMH',
    titleEs: 'Depresión: conceptos según el NIMH',
    excerptFr: 'Définition grand public tirée du National Institute of Mental Health.',
    excerptEn: 'Consumer-definition excerpt from NIH/NIMH.',
    excerptEs: 'Extracto definitorio del NIMH (NIH).',
    bodyFr:
      '<p>Rappel&nbsp;: texte ci-dessous en anglais tel que publié par le NIH.</p><blockquote cite="https://www.nimh.nih.gov/health/topics/depression"><p>Everyone feels sad or low sometimes, but these feelings usually pass with time.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nimh.nih.gov/health/topics/depression" rel="noopener noreferrer">NIH/NIMH — Depression</a>, mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Depressive disorders are clinically serious; public-health agencies distinguish passing low mood from illnesses that need treatment.</p><blockquote cite="https://www.nimh.nih.gov/health/topics/depression"><p>Everyone feels sad or low sometimes, but these feelings usually pass with time.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nimh.nih.gov/health/topics/depression" rel="noopener noreferrer">National Institute of Mental Health</a>. Accessed May&nbsp;2026. U.S. government work—not a substitute for professional assessment.</p>',
    bodyEs:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/depression"><p>Everyone feels sad or low sometimes, but these feelings usually pass with time.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nimh.nih.gov/health/topics/depression" rel="noopener noreferrer">NIMH</a>.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000004',
    slug: 'nimh-anxiety-disorders',
    datePublished: '2026-01-22',
    titleFr: 'Troubles anxieux — excerpt NIMH',
    titleEn: 'Anxiety disorders: NIH/NIMH primer',
    titleEs: 'Trastornos de ansiedad — NIMH',
    excerptFr: 'Citation courte sur l’anxiété telle que présentée aux patient·e·s par le NIH.',
    excerptEn: 'Quoted consumer paragraph on anxiety disorders from NIMH.',
    excerptEs: 'Párrafo para el público sobre ansiedad.',
    bodyFr:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/anxiety-disorders"><p>Feeling anxious is a normal part of life.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" rel="noopener noreferrer">NIH/NIMH — Anxiety Disorders</a>, mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Distinguishing everyday worry from disorders that merit clinical attention is a core psychoeducation topic.</p><blockquote cite="https://www.nimh.nih.gov/health/topics/anxiety-disorders"><p>Feeling anxious is a normal part of life.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" rel="noopener noreferrer">NIH/NIMH — Anxiety Disorders</a>. Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/anxiety-disorders"><p>Feeling anxious is a normal part of life.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nimh.nih.gov/health/topics/anxiety-disorders" rel="noopener noreferrer">NIMH</a>.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000005',
    slug: 'nimh-adhd-overview',
    datePublished: '2026-02-02',
    titleFr: 'TDAH chez enfants et ados — NIMH',
    titleEn: 'ADHD in children and teens — NIMH facts',
    titleEs: 'TDAH en niños y adolescentes — NIMH',
    excerptFr: 'Début de la page grand public NIH sur le TDAH.',
    excerptEn: 'Leading sentence from NIH’s ADHD consumer topic page.',
    excerptEs: 'Frase inicial de la página del NIMH.',
    bodyFr:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd"><p>ADHD is one of the most common disorders diagnosed in children.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd" rel="noopener noreferrer">NIH/NIMH — ADHD</a>, mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Federal descriptions highlight that ADHD begins in childhood yet often persists, which shapes treatment planning across the lifespan.</p><blockquote cite="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd"><p>ADHD is one of the most common disorders diagnosed in children.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd" rel="noopener noreferrer">NIH/NIMH — ADHD</a>. Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd"><p>ADHD is one of the most common disorders diagnosed in children.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd" rel="noopener noreferrer">NIMH</a>.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000006',
    slug: 'nimh-ptsd-basics',
    datePublished: '2026-02-08',
    titleFr: 'État de stress post-traumatique — NIMH',
    titleEn: 'Post-traumatic stress disorder — NIMH',
    titleEs: 'Trastorno de estrés postraumático — NIMH',
    excerptFr: 'Définition clinique vulgarisée par le NIH.',
    excerptEn: 'Quoted plain-language PTSD definition.',
    excerptEs: 'Definición para el público.',
    bodyFr:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd"><p>People may be diagnosed with post-traumatic stress disorder (PTSD) if their symptoms last for an extended period after a traumatic event and begin to interfere with aspects of daily life, such as relationships or work.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd" rel="noopener noreferrer">NIH/NIMH — PTSD</a>, mai&nbsp;2026.</p>',
    bodyEn:
      '<p>PTSD criteria emphasize functional impairment long after the traumatic cue; early psychoeducation can normalize help-seeking.</p><blockquote cite="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd"><p>People may be diagnosed with post-traumatic stress disorder (PTSD) if their symptoms last for an extended period after a traumatic event and begin to interfere with aspects of daily life, such as relationships or work.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd" rel="noopener noreferrer">NIH/NIMH — PTSD</a>. Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd"><p>People may be diagnosed with post-traumatic stress disorder (PTSD) if their symptoms last for an extended period after a traumatic event and begin to interfere with aspects of daily life, such as relationships or work.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nimh.nih.gov/health/topics/post-traumatic-stress-disorder-ptsd" rel="noopener noreferrer">NIMH</a>.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000007',
    slug: 'nhlbi-why-sleep-matters',
    datePublished: '2026-02-14',
    titleFr: 'Pourquoi le sommeil compte pour la santé (NIH/NHLBI)',
    titleEn: 'Why sleep health matters — NHLBI (NIH)',
    titleEs: 'Por qué importa dormir bien — NHLBI',
    excerptFr: 'Message de prévention cardiorespiratoire sur le sommeil.',
    excerptEn: 'Quoted prevention messaging from NIH’s National Heart, Lung, and Blood Institute.',
    excerptEs: 'Mensaje de prevención del NHLBI.',
    bodyFr:
      '<blockquote cite="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important"><p>Sleep plays a vital role in good health and well-being throughout your life.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important" rel="noopener noreferrer">National Heart, Lung, and Blood Institute (NIH)</a>, mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Sleep interacts with cardiovascular, metabolic, and mental health outcomes; NHLBI summarizes why healthy sleep hygiene matters alongside medical care.</p><blockquote cite="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important"><p>Sleep plays a vital role in good health and well-being throughout your life.</p></blockquote><p><strong>Source:</strong> <a href="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important" rel="noopener noreferrer">NHLBI — Why Is Sleep Important?</a> Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important"><p>Sleep plays a vital role in good health and well-being throughout your life.</p></blockquote><p><strong>Fuente:</strong> <a href="https://www.nhlbi.nih.gov/health/sleep/why-sleep-important" rel="noopener noreferrer">NHLBI (NIH)</a>.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000008',
    slug: 'who-adolescent-mental-health',
    datePublished: '2026-02-20',
    titleFr: 'Santé mentale des adolescent·e·s — OMS',
    titleEn: 'Adolescent mental health — WHO fact sheet',
    titleEs: 'Salud mental de adolescentes — OMS',
    excerptFr: 'Données mondiales tirées de la fiche OMS.',
    excerptEn: 'Global prevalence snippet from WHO’s adolescent mental health factsheet.',
    excerptEs: 'Datos globales según la OMS.',
    bodyFr:
      '<p>L’OMS autorise la reproduction de ses fiches factuelles avec la mention de source indiquée sur le site.</p><blockquote cite="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health"><p>Globally, one in seven 10-19-year-olds experiences a mental disorder, accounting for 15% of the global burden of disease in this age group.</p></blockquote><p><strong>Source&nbsp;:</strong> World Health Organization, <em>Mental health of adolescents</em> fact sheet, <a href="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health" rel="noopener noreferrer">who.int</a>, consulté mai&nbsp;2026.</p>',
    bodyEn:
      '<p>WHO highlights the population-level burden of adolescent mental disorders to argue for school- and community-based prevention.</p><blockquote cite="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health"><p>Globally, one in seven 10-19-year-olds experiences a mental disorder, accounting for 15% of the global burden of disease in this age group.</p></blockquote><p><strong>Source:</strong> World Health Organization, <em>Mental health of adolescents</em> fact sheet (<a href="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health" rel="noopener noreferrer">who.int</a>). Accessed May&nbsp;2026. Follow WHO credit lines when republishing.</p>',
    bodyEs:
      '<blockquote cite="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health"><p>Globally, one in seven 10-19-year-olds experiences a mental disorder, accounting for 15% of the global burden of disease in this age group.</p></blockquote><p><strong>Fuente:</strong> OMS, ficha sobre salud mental de los adolescentes (<a href="https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health" rel="noopener noreferrer">who.int</a>).</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000009',
    slug: '988-suicide-and-crisis-lifeline',
    datePublished: '2026-03-01',
    titleFr: 'Ligne nationale 988 (États-Unis) pour la détresse',
    titleEn: '988 Suicide & Crisis Lifeline (United States)',
    titleEs: 'Línea 988 de crisis en EE.&nbsp;UU.',
    excerptFr: 'Présentation officielle gratuite disponible jour et nuit.',
    excerptEn: 'Quoted description from the federally supported 988lifeline.org site.',
    excerptEs: 'Texto oficial del servicio 988.',
    bodyFr:
      '<blockquote cite="https://988lifeline.org/"><p>Through the 988 Lifeline, you have access to free, quality, one-on-one assistance.</p></blockquote><p><strong>Source&nbsp;:</strong> <a href="https://988lifeline.org/" rel="noopener noreferrer">988 Suicide&nbsp;&amp; Crisis Lifeline</a>. Service américain gratuit 24&nbsp;h/24 — consulté mai&nbsp;2026.</p>',
    bodyEn:
      '<p>Crisis hotlines stabilize immediate risk until local emergency responders or outpatient teams can intervene. The U.S. 988 Lifeline routes texts and calls nationally.</p><blockquote cite="https://988lifeline.org/"><p>Through the 988 Lifeline, you have access to free, quality, one-on-one assistance.</p></blockquote><p><strong>Source:</strong> <a href="https://988lifeline.org/" rel="noopener noreferrer">988 Suicide &amp; Crisis Lifeline</a>. Accessed May&nbsp;2026. Not affiliated with PsyNova; verify instructions on the linked site.</p>',
    bodyEs:
      '<blockquote cite="https://988lifeline.org/"><p>Through the 988 Lifeline, you have access to free, quality, one-on-one assistance.</p></blockquote><p><strong>Fuente:</strong> <a href="https://988lifeline.org/" rel="noopener noreferrer">988 Lifeline</a> (EE. UU.).</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000010',
    slug: 'cdc-mental-health-resources-hotlines',
    datePublished: '2026-03-06',
    titleFr: 'Ressources de crise américaines (CDC)',
    titleEn: 'Crisis-ready mental-health resources — CDC',
    titleEs: 'Recursos y líneas de crisis — CDC',
    excerptFr: 'Points saillants des pages CDC sur l’aide immédiate (anglais original).',
    excerptEn: 'Quoted key points covering hotlines from CDC’s Mental Health Resources page.',
    excerptEs: 'Extracto de páginas públicas CDC.',
    bodyFr:
      '<blockquote cite="https://www.cdc.gov/mental-health/caring/index.html"><p>If you need help now, call a crisis hotline to get immediate emergency counseling.</p></blockquote><p><strong>Source&nbsp;:</strong> Centers for Disease Control and Prevention, <em>Mental Health Resources</em>, <a href="https://www.cdc.gov/mental-health/caring/index.html" rel="noopener noreferrer">cdc.gov</a>, consulté mai&nbsp;2026.</p>',
    bodyEn:
      '<p>U.S. federal pages cluster national hotlines alongside tips for locating ongoing care.</p><blockquote cite="https://www.cdc.gov/mental-health/caring/index.html"><p>If you need help now, call a crisis hotline to get immediate emergency counseling.</p></blockquote><p><strong>Source:</strong> Centers for Disease Control and Prevention (<a href="https://www.cdc.gov/mental-health/caring/index.html" rel="noopener noreferrer">Mental Health Resources</a>). Accessed May&nbsp;2026.</p>',
    bodyEs:
      '<blockquote cite="https://www.cdc.gov/mental-health/caring/index.html"><p>If you need help now, call a crisis hotline to get immediate emergency counseling.</p></blockquote><p><strong>Fuente:</strong> CDC (<a href="https://www.cdc.gov/mental-health/caring/index.html" rel="noopener noreferrer">cdc.gov</a>).</p>',
    published: true,
    updatedAt: now(),
  },
];

export function cloneCmsMemory() {
  return {
    media: structuredClone(CMS_SEED_MEDIA),
    doctors: structuredClone(CMS_SEED_DOCTORS),
    services: structuredClone(CMS_SEED_SERVICES),
    testimonials: structuredClone(CMS_SEED_TESTIMONIALS),
    homeSections: structuredClone(CMS_SEED_HOME),
    blogPosts: structuredClone(CMS_SEED_BLOG),
  };
}
