import type {
  CmsBlogPostRow,
  CmsDoctorRow,
  CmsHomeSectionRow,
  CmsMediaRow,
  CmsServiceRow,
  CmsTestimonialRow,
} from './cms.types';

/** Mirrors database/06-cms-seed.sql for USE_PERSISTENCE=false. */
export const CMS_SEED_MEDIA: CmsMediaRow[] = [
  {
    id: 'a0000001-0000-4000-8000-000000000001',
    storagePath: null,
    publicUrl:
      'https://api.dicebear.com/7.x/micah/svg?seed=DrLunaBrightmind&backgroundColor=b6e3f4',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Dr. Luna Brightmind',
    altEn: 'Cartoon avatar — Dr. Luna Brightmind',
    altEs: 'Avatar cartoon — Dra. Luna Brightmind',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000002',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=MiloDreamleaf&backgroundColor=d1f4e0',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Milo Dreamleaf',
    altEn: 'Cartoon avatar — Milo Dreamleaf',
    altEs: 'Avatar cartoon — Milo Dreamleaf',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000003',
    storagePath: null,
    publicUrl:
      'https://api.dicebear.com/7.x/micah/svg?seed=AlexCloudwalker&backgroundColor=e8d5f2',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — Alex Cloudwalker',
    altEn: 'Cartoon avatar — Alex Cloudwalker',
    altEs: 'Avatar cartoon — Alex Cloudwalker',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000004',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientAvery&backgroundColor=fff4e6',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000005',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientJordan&backgroundColor=f0f4ff',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
  {
    id: 'a0000001-0000-4000-8000-000000000006',
    storagePath: null,
    publicUrl: 'https://api.dicebear.com/7.x/micah/svg?seed=PatientSam&backgroundColor=fce4ec',
    mimeType: 'image/svg+xml',
    altFr: 'Avatar cartoon — témoignage',
    altEn: 'Cartoon avatar — patient testimonial',
    altEs: 'Avatar cartoon — testimonio',
  },
];

const now = () => new Date().toISOString();

export const CMS_SEED_DOCTORS: CmsDoctorRow[] = [
  {
    id: 'd0000001-0000-4000-8000-000000000001',
    slug: 'luna',
    sortOrder: 0,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000001',
    nameFr: 'Dr. Luna Brightmind',
    nameEn: 'Dr. Luna Brightmind',
    nameEs: 'Dra. Luna Brightmind',
    roleFr: 'Psychologue',
    roleEn: 'Psychologist',
    roleEs: 'Psicóloga',
    bioFr: '<p>Approche intégrative TCC et pleine conscience. Focus sur l’anxiété et les transitions de vie.</p>',
    bioEn: '<p>Integrative CBT and mindfulness. Focus on anxiety and life transitions.</p>',
    bioEs: '<p>TCC integrativa y mindfulness. Ansiedad y transiciones vitales.</p>',
    illustrationNote: 'Semi-flat portrait, soft teal and cream palette, warm smile — calm professionalism.',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'd0000001-0000-4000-8000-000000000002',
    slug: 'milo',
    sortOrder: 1,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000002',
    nameFr: 'Milo Dreamleaf',
    nameEn: 'Milo Dreamleaf',
    nameEs: 'Milo Dreamleaf',
    roleFr: 'Travailleur social clinique',
    roleEn: 'Clinical social worker',
    roleEs: 'Trabajador social clínico',
    bioFr: '<p>Soutien aux familles et aux jeunes; perspective systémique.</p>',
    bioEn: '<p>Supports families and youth; systemic lens.</p>',
    bioEs: '<p>Apoyo a familias y jóvenes; enfoque sistémico.</p>',
    illustrationNote: 'Pastel greens, seated figure with plant motif — inclusive silhouette.',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'd0000001-0000-4000-8000-000000000003',
    slug: 'alex',
    sortOrder: 2,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000003',
    nameFr: 'Alex Cloudwalker',
    nameEn: 'Alex Cloudwalker',
    nameEs: 'Alex Cloudwalker',
    roleFr: 'Psychothérapeute',
    roleEn: 'Psychotherapist',
    roleEs: 'Psicoterapeuta',
    bioFr: '<p>Affirmatif 2SLGBTQ+; thérapie axée sur les forces et la résilience.</p>',
    bioEn: '<p>2SLGBTQ+-affirming; strengths-based, resilience-focused care.</p>',
    bioEs: '<p>Afirmativo 2SLGBTQ+; enfoque en fortalezas y resiliencia.</p>',
    illustrationNote: 'Soft lavender and sky blue, abstract path motif — recovery-oriented.',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_SERVICES: CmsServiceRow[] = [
  {
    id: 'e0000001-0000-4000-8000-000000000001',
    slug: 'individual',
    sortOrder: 0,
    titleFr: 'Thérapie individuelle',
    titleEn: 'Individual therapy',
    titleEs: 'Terapia individual',
    bodyFr: '<p>Suivi psychologique individuel (adultes).</p>',
    bodyEn: '<p>One-to-one psychological care (adults).</p>',
    bodyEs: '<p>Atención psicológica individual (adultos).</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000002',
    slug: 'couples',
    sortOrder: 1,
    titleFr: 'Couple',
    titleEn: 'Couples',
    titleEs: 'Pareja',
    bodyFr: '<p>Soutien relationnel et médiation thérapeutique.</p>',
    bodyEn: '<p>Relationship support and therapeutic mediation.</p>',
    bodyEs: '<p>Apoyo relacional y mediación terapéutica.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000003',
    slug: 'family',
    sortOrder: 2,
    titleFr: 'Famille',
    titleEn: 'Family',
    titleEs: 'Familia',
    bodyFr: '<p>Séances impliquant plusieurs membres de la famille.</p>',
    bodyEn: '<p>Sessions involving multiple family members.</p>',
    bodyEs: '<p>Sesiones con varios miembros de la familia.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000004',
    slug: 'youth',
    sortOrder: 3,
    titleFr: 'Jeunesse (12–17)',
    titleEn: 'Youth (12–17)',
    titleEs: 'Juventud (12–17)',
    bodyFr: '<p>Accompagnement adapté aux adolescents.</p>',
    bodyEn: '<p>Developmentally appropriate adolescent support.</p>',
    bodyEs: '<p>Acompañamiento adaptado a adolescentes.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000005',
    slug: 'anxiety_mood',
    sortOrder: 4,
    titleFr: 'Anxiété & humeur',
    titleEn: 'Anxiety & mood',
    titleEs: 'Ansiedad y estado de ánimo',
    bodyFr: '<p>Symptômes d’anxiété, dépression, stress.</p>',
    bodyEn: '<p>Anxiety, depression, and stress-related symptoms.</p>',
    bodyEs: '<p>Ansiedad, depresión y estrés.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000006',
    slug: 'adhd_focus',
    sortOrder: 5,
    titleFr: 'TDAH / attention',
    titleEn: 'ADHD / attention',
    titleEs: 'TDAH / atención',
    bodyFr: '<p>Difficultés d’attention, organisation, exécution.</p>',
    bodyEn: '<p>Attention, organization, and executive functioning.</p>',
    bodyEs: '<p>Atención, organización y funciones ejecutivas.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000007',
    slug: 'trauma',
    sortOrder: 6,
    titleFr: 'Trauma informé',
    titleEn: 'Trauma-informed',
    titleEs: 'Informado en trauma',
    bodyFr: '<p>Approches sensibles aux vécu traumatiques.</p>',
    bodyEn: '<p>Trauma-sensitive clinical approaches.</p>',
    bodyEs: '<p>Enfoques sensibles al trauma.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000008',
    slug: 'assessment',
    sortOrder: 7,
    titleFr: 'Évaluation',
    titleEn: 'Assessment',
    titleEs: 'Evaluación',
    bodyFr: '<p>Bilan orienté diagnostic ou orientation de services.</p>',
    bodyEn: '<p>Diagnostic-oriented or service-planning assessment.</p>',
    bodyEs: '<p>Evaluación orientada al diagnóstico o planificación.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'e0000001-0000-4000-8000-000000000009',
    slug: 'other',
    sortOrder: 8,
    titleFr: 'Autre',
    titleEn: 'Other',
    titleEs: 'Otro',
    bodyFr: '<p>Précisez dans les notes au clinicien.</p>',
    bodyEn: '<p>Add details in notes to clinician.</p>',
    bodyEs: '<p>Detalles en notas al clínico.</p>',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_TESTIMONIALS: CmsTestimonialRow[] = [
  {
    id: 'f0000001-0000-4000-8000-000000000001',
    sortOrder: 0,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000004',
    authorFr: 'Avery L. (fictif)',
    authorEn: 'Avery L. (fictional)',
    authorEs: 'Avery L. (ficticio)',
    quoteFr: '<p>Interface claire pour la démo — aucune donnée réelle, mais le parcours est rassurant.</p>',
    quoteEn: '<p>Clear interface for the demo — no real data, but the flow feels reassuring.</p>',
    quoteEs: '<p>Interfaz clara para la demo — sin datos reales, pero el flujo transmite calma.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'f0000001-0000-4000-8000-000000000002',
    sortOrder: 1,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000005',
    authorFr: 'Jordan M. (fictif)',
    authorEn: 'Jordan M. (fictional)',
    authorEs: 'Jordan M. (ficticio)',
    quoteFr: '<p>La prise de rendez-vous guidée est utile pour valider l’ergonomie.</p>',
    quoteEn: '<p>Guided booking helps validate the ergonomics.</p>',
    quoteEs: '<p>La reserva guiada ayuda a validar la ergonomía.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'f0000001-0000-4000-8000-000000000003',
    sortOrder: 2,
    avatarMediaId: 'a0000001-0000-4000-8000-000000000006',
    authorFr: 'Sam R. (fictif)',
    authorEn: 'Sam R. (fictional)',
    authorEs: 'Sam R. (ficticio)',
    quoteFr: '<p>Contenu trilingue cohérent pour une maquette pédagogique.</p>',
    quoteEn: '<p>Consistent trilingual content for an educational mockup.</p>',
    quoteEs: '<p>Contenido trilingüe coherente para una maqueta educativa.</p>',
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_HOME: CmsHomeSectionRow[] = [
  {
    id: 'b0000001-0000-4000-8000-000000000001',
    sortOrder: 0,
    sectionType: 'hero',
    payload: {
      title: {
        fr: 'Clinique virtuelle de psychologie — Montréal',
        en: 'Virtual psychology clinic — Montreal',
        es: 'Clínica virtual de psicología — Montreal',
      },
      lead: {
        fr: 'Accompagnement psychologique téléphonique et en visioconférence. Maquette à des fins de démonstration — aucun service clinique réel.',
        en: 'Telephone and video support (mockup). Demonstration only — no real clinical service.',
        es: 'Acompañamiento por teléfono y videollamada. Maqueta de demostración — sin servicio clínico real.',
      },
      ctaPrimary: {
        label: { fr: 'Créer un compte fictif', en: 'Create a demo account', es: 'Cuenta de demostración' },
        href: '#/register',
      },
      ctaSecondary: {
        label: { fr: 'Avis légaux', en: 'Legal notices', es: 'Avisos legales' },
        href: '#/legal',
      },
      ctaBook: {
        label: { fr: 'Prendre rendez-vous', en: 'Book a session', es: 'Reservar' },
        href: '#/login',
      },
    },
    published: true,
    updatedAt: now(),
  },
  {
    id: 'b0000001-0000-4000-8000-000000000002',
    sortOrder: 1,
    sectionType: 'feature_grid',
    payload: {
      cards: [
        {
          title: { fr: 'Services', en: 'Services', es: 'Servicios' },
          blurb: {
            fr: 'Les catégories relient le formulaire de réservation une fois connecté.',
            en: 'Categories connect to booking after sign-in.',
            es: 'Las categorías enlazan con la reserva tras iniciar sesión.',
          },
          href: '#/services',
        },
        {
          title: { fr: 'Équipe', en: 'Team', es: 'Equipo' },
          blurb: {
            fr: 'Personnages fictifs et avatars cartoon.',
            en: 'Fictional characters and cartoon avatars.',
            es: 'Personajes ficticios y avatares cartoon.',
          },
          href: '#/team',
        },
        {
          title: { fr: 'Blogue', en: 'Blog', es: 'Blog' },
          blurb: {
            fr: 'Articles pédagogiques d’exemple.',
            en: 'Educational sample posts.',
            es: 'Artículos educativos de ejemplo.',
          },
          href: '#/blog',
        },
      ],
    },
    published: true,
    updatedAt: now(),
  },
  {
    id: 'b0000001-0000-4000-8000-000000000003',
    sortOrder: 2,
    sectionType: 'testimonial_strip',
    payload: {
      heading: {
        fr: 'Témoignages (fictifs)',
        en: 'Testimonials (fictional)',
        es: 'Testimonios (ficticios)',
      },
    },
    published: true,
    updatedAt: now(),
  },
];

export const CMS_SEED_BLOG: CmsBlogPostRow[] = [
  {
    id: 'c0000001-0000-4000-8000-000000000001',
    slug: 'hiver-montréal',
    datePublished: '2026-01-15',
    titleFr: 'L’hiver à Montréal et l’humeur : pistes d’auto-soins',
    titleEn: 'Montreal winters and mood: gentle self-care ideas',
    titleEs: 'Invierno en Montreal y el ánimo: ideas de autocuidado',
    excerptFr: 'Lumière, mouvement et lien social : rappels non médicalisés pour une maquette pédagogique.',
    excerptEn: 'Light, movement, connection — educational mockup, not medical advice.',
    excerptEs: 'Luz, movimiento y vínculos — contenido educativo de maqueta.',
    bodyFr:
      '<p>Ceci est un <strong>article fictif</strong>. En pratique, un professionnel peut recommander luminothérapie validée, activité physique adaptée et suivis personnalisés.</p><p>Aucune donnée réelle ; viser une revue clinique avant publication.</p>',
    bodyEn:
      '<p>This is a <strong>fictional article</strong>. In real care, clinicians may suggest evidence-based light therapy, tailored exercise, and follow-up.</p><p>No real data; clinical review required before live use.</p>',
    bodyEs: '<p>Artículo <strong>ficticio</strong>. En la práctica clínica real se personalizan intervenciones con evidencia.</p>',
    published: true,
    updatedAt: now(),
  },
  {
    id: 'c0000001-0000-4000-8000-000000000002',
    slug: 'telepsychologie-quebec',
    datePublished: '2026-02-01',
    titleFr: 'Télépsychologie au Québec : attentes réalistes',
    titleEn: 'Telepsychology in Quebec: realistic expectations',
    titleEs: 'Telepsicología en Quebec: expectativas realistas',
    excerptFr: 'Confidentialité, consentement et limites technologiques — rappel pour la maquette.',
    excerptEn: 'Privacy, consent, tech limits — mockup reminder.',
    excerptEs: 'Privacidad, consentimiento y límites técnicos.',
    bodyFr:
      '<p>La télépsychologie peut améliorer l’accès ; elle ne convient pas à toutes les situations. L’urgence vitale reste hors plateforme.</p>',
    bodyEn:
      '<p>Telepsychology can improve access; it is not for every situation. Life-threatening emergencies belong off-platform.</p>',
    bodyEs: '<p>Mejora el acceso pero no sustituye la emergencia presencial cuando hace falta.</p>',
    published: true,
    updatedAt: now(),
  },
];

export function cloneCmsMemory() {
  return {
    media: structuredClone(CMS_SEED_MEDIA),
    doctors: structuredClone(CMS_SEED_DOCTORS),
    services: structuredClone(CMS_SEED_SERVICES),
    testimonials: structuredClone(CMS_SEED_TESTIMONIALS),
    homeSections: structuredClone(CMS_SEED_HOME),
    blogPosts: structuredClone(CMS_SEED_BLOG),
  };
}
